import { FDADevice } from "@/types";

export const MOCK_FDA_DEVICES: FDADevice[] = [
  // Cardiovascular
  {
    k_number: "K070213",
    device_name: "PERFORMER CBP SYSTEM",
    applicant: "RAND S.R.L.",
    date_received: "2007-01-15",
    decision_date: "2007-03-21",
    decision_description: "Substantially Equivalent",
    product_code: "DWE",
    statement_or_summary: "Cardiopulmonary bypass system",
    advisory_committee_description: "Cardiovascular",
    openfda: { device_class: "2" },
    predicate_device_numbers: ["K980016"],
  },
  {
    k_number: "K980016",
    device_name: "MILLENNIUM VALVE INTRODUCER/ROTATOR HANDLE",
    applicant: "GENZYME SURGICAL PRODUCT (GENZYME CORP.)",
    date_received: "1998-06-10",
    decision_date: "1998-08-07",
    decision_description: "Substantially Equivalent",
    product_code: "DTK",
    statement_or_summary: "Heart valve delivery system",
    advisory_committee_description: "Cardiovascular",
    openfda: { device_class: "1" },
    predicate_device_numbers: ["K791630"],
  },
  {
    k_number: "K791630",
    device_name: "BRAIN HEART INFUSION AGAR",
    applicant: "ISLE MEDIA AND STERILE PRODUCTS, INC.",
    date_received: "1979-08-15",
    decision_date: "1979-09-27",
    decision_description: "Substantially Equivalent",
    product_code: "JJX",
    statement_or_summary: "Culture media for diagnostic use",
    advisory_committee_description: "Microbiology",
    openfda: { device_class: "1" },
    predicate_device_numbers: [],
  },

  // Orthopedic
  {
    k_number: "K123456",
    device_name: "TITANIUM HIP IMPLANT SYSTEM",
    applicant: "ORTHOPEDIC INNOVATIONS INC.",
    date_received: "2020-03-15",
    decision_date: "2020-06-22",
    decision_description: "Substantially Equivalent",
    product_code: "KWL",
    statement_or_summary: "Hip replacement system",
    advisory_committee_description: "Orthopedic",
    openfda: { device_class: "2" },
    predicate_device_numbers: ["K098765"],
  },
  {
    k_number: "K098765",
    device_name: "CERAMIC JOINT REPLACEMENT",
    applicant: "ADVANCED MATERIALS CORP.",
    date_received: "2015-11-08",
    decision_date: "2016-01-14",
    decision_description: "Substantially Equivalent",
    product_code: "KWL",
    statement_or_summary: "Ceramic hip joint component",
    advisory_committee_description: "Orthopedic",
    openfda: { device_class: "2" },
    predicate_device_numbers: ["K791630"],
  },

  // Diagnostic
  {
    k_number: "K234567",
    device_name: "AI-POWERED DIAGNOSTIC SCANNER",
    applicant: "MEDTECH SOLUTIONS LLC",
    date_received: "2023-01-10",
    decision_date: "2023-04-18",
    decision_description: "Substantially Equivalent",
    product_code: "MRI",
    statement_or_summary: "Machine learning diagnostic imaging",
    advisory_committee_description: "Radiology",
    openfda: { device_class: "2" },
    predicate_device_numbers: [],
  },
];
